### ISSUE TITLE
WindowsServerのnifcloud_instance作成時のディスク構成について

### ISSUE THREAD

**Issue by ju-asao** [nifcloud/terraform-provider-nifcloud#143]
WindowsServerのnifcloud_instanceを作成した際はデフォルトでCドライブ
の80Gディスクが作成されますでしょうか？

**Comment by fuku2014** [comment]
@ju-asao 

Yes, this will create a server with basic disk capacity (Linux: 30GB, Windows: 80GB), just like when creating it with the control panel.

**Comment by ju-asao** [comment]
@fuku2014 
OK, thank you very much.
