### ISSUE TITLE
nifcloud_instanceのパラメータ key_nameについて

### ISSUE THREAD

**Issue by ju-asao** [nifcloud/terraform-provider-nifcloud#145]
nifcloud_instanceのパラメータの中で "key_name"は何に使用するのでしょ
うか？
OSがWindows Serverの場合は
こちらを指定することは必須でしょうか？

**Comment by fuku2014** [comment]
Hello @ju-asao,

The `key_name` can only be specified for Linux servers for ssh key and is not required when creating Windows servers.
Thanks.

**Comment by ju-asao** [comment]
Hello @fuku2014 ,
I understand your answer.
I am very grateful for your response.
Thanks.
> Hello @ju-asao,
> 
> The `key_name` can only be specified for Linux servers for ssh key and is not required when creating Windows servers. Thanks.
