### ISSUE TITLE
OSイメージの指定について (Windows Server 2022)

### ISSUE THREAD

**Issue by ju-asao** [nifcloud/terraform-provider-nifcloud#146]
teraformでwindows Server 2022のOSイメージを指定する場合とWindows Server
2022 + SQLServer 2022 OSイメージを指定する場合の
それぞれのimage_nameは何になりますでしょうか？

パターン(1)
Windows Serverのみ
OS：Microsoft Windows Server 2022 Datacenter Edition（64bit）
image_name =?

パターン(2)
Windows Server + SQL Server
OS：Microsoft Windows Server 2022 Datacenter Edition（64bit）
SQLServer：Microsoft SQL Server 2022 Standard Edition
image_name =?

data "nifcloud_image" "任意の値" {
image_name = "XXXXXX" →この値が知りたい
}

**Comment by fuku2014** [comment]
@ju-asao 

Please try below!

pattern 1
`Windows Server 2022 DC`
pattern 2
`Windows Server 2022 DC + SQL Server 2022 Std`

**Comment by ju-asao** [comment]
@fuku2014 
I See, Thank you very much
