### ISSUE TITLE
RDBの作成でステータスが「エラー」になった場合の即時復帰について

### ISSUE THREAD

**Issue by yossea117** [nifcloud/terraform-provider-nifcloud#72]
RDBの作成でステータスが「エラー」になった場合でも、タイムアウトするまで復帰しません。エラーになった場合に即時復帰できないでしょうか？

```
nifcloud_db_instance.dbserver02: Still creating... [52m52s elapsed]

Error: failed waiting for db instance to become ready: ResourceNotReady: exceeded wait attempts

```

![image](https://user-images.githubusercontent.com/11656346/122852567-d2f1c500-d34b-11eb-99ce-093ddc7afb6f.png)

**Comment by fuku2014** [comment]
Hi @yossea117 

Thanks for the tip! It will be fixed in a future release.

**Comment by fuku2014** [comment]
Fixed for v1.4.0 release🎉
