### ISSUE TITLE
Router creation fails with v.1.4.0

### ISSUE THREAD

**Issue by takaeda-hiroaki** [nifcloud/terraform-provider-nifcloud#88]
# Provider version
terraform-provider-nifcloud v1.4.0

# Terraform Configuration File

<pre>
resource "nifcloud_private_lan" "privatelan01" {
    private_lan_name  = "plan1"
    availability_zone = "east-12"
    cidr_block        = "192.168.1.0/24"
    accounting_type   = "2"
}

resource "nifcloud_router" "router01" {
    name              = "router1"
    availability_zone = "east-12"
    type              = "small"
    accounting_type   = "2"
    description       = "router 1"
    network_interface {
        network_id      = "net-COMMON_PRIVATE"
    }
    network_interface {
        network_name    = nifcloud_private_lan.privatelan01.private_lan_name
        ip_address      = "192.168.1.11"
    }
}
</pre>

# Steps to Reproduce
Use the above configuration and execute apply. Then, error occures.
The error message is as follows:

<pre>
    Error: failed creating router: Client.Inoperable.Network.CommonNetwork: DhcpConfiguration cannot set to CommonGlobal and CommonPrivate.
            status code: 500, request id: a788e3c9-5d13-4d2c-a794-0d4965ddae32
  
      on fjcloud-v.tf line 23, in resource "nifcloud_router" "router01":
      23: resource "nifcloud_router" "router01" {
</pre>

# Supplement
There is no problem with v1.3.2

**Comment by tily** [comment]
@takaeda-hiroaki Thanks for the report.
From terraform-provider-nifcloud v1.4.0, the router's `network_interface.dhcp` attribute defaults to true instead of false,
so please specify `dhcp = false` explicitly when you want to create the router with common-private network.
