### ISSUE TITLE
リモートアクセスVPNGWを作成するコマンドについて

### ISSUE THREAD

**Issue by KatsujiYoshimura** [nifcloud/terraform-provider-nifcloud#99]
リモートアクセスVPNGWを作成するコマンドがありません。
今後提供されますでしょうか？予定を教えていただけますでしょうか？
以上、よろしくお願いします。

**Comment by tily** [comment]
@KatsujiYoshimura 

Thanks for the question.
Currently, NIFCLOUD Computing does not provide RemoteAccessVPNGateway-related web APIs yet,
so we will plan to integrate them after the APIs are released.

**Comment by aokumasan** [comment]
Good news!
Remote Access VPN Gateway is now supported by nifcloud-sdk-go.
We will plan to implement the `nifcloud_remote_access_vpn_gateway` resource in the not too distant future.

**Comment by fuku2014** [comment]
Good news!

Finally implemented in v1.9.0 🚀 
Try it and Enjoy!
